### PR TITLE
Convert RapidAddon to use namespaces and autoloading

### PR DESCRIPTION
**Pull request by claytoncollie**
This PR converts the RapidAdd on class to use a namespace and autoload the main file when pulling it in via Composer. My hope is that more of your plugins will be able to use Composer in the future so I am trying to do a small part to help you along that path.

### CODE REVIEW

**Comment by claytoncollie** [comment]
After thinking about this some more, I could also see the namespace being `Soflyy\WpAllImportRapidAddon` which would then make the `RapidAddon` class `Soflyy\WpAllImportRapidAddon\RapidAddon`.  That might not be such a big deal to have the RapidAddon duplication and it scopes the plugin a little tighter. 

People can always use an alias to simplify their code.

```use Soflyy\WpAllImportRapidAddon\RapidAddon as RapidAddon;```

**Comment by joeguilmette** [comment]
Thanks Clayton! This is definitely on our list and this is definitely a push in the right direction.

**Comment by Programmer095** [comment]
I'm going to merge this into a feature branch as we will need to make further adjustments for our workflows.

**Comment by Programmer095** [comment]
This now exists on a feature branch: https://github.com/soflyy/wp-all-import-rapid-addon/tree/feature/composer-support

**Pull request closed without merging**
